spring:
  datasource:
    url: jdbc:mysql://mainline.proxy.rlwy.net:18164/railway
    username: root
    password: fMtZECeohCYGzYCaImhswlXLAhujgUwv
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update

